theme: jekyll-theme-slate
title: [Thomas Meany (personal website)]
description: [Sharing projects I work on and a bit about me]
github:
  repository_url: https://github.com/tmopencell
  another_url: https://opencell.bio
